name: CI/CD Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pip install bandit

      # 1. Quét lỗ hổng trong mã nguồn (SAST)
      - name: Run Bandit Security Analysis
        run: |
          echo "Running Bandit static analysis..."
          bandit -r . -f txt || true

      # 2. Kiểm tra lộ secret (token/API key)
      - name: Detect Secrets with Gitleaks
        uses: gitleaks/gitleaks-action@v2

      # 3. Quét lỗ hổng hệ thống và dependencies (Vulnerability Scan)
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'

      # 4. Build và kiểm thử ứng dụng (Demo)
      - name: Build and Test (demo)
        run: |
          echo "Build thành công!"
          echo "CI/CD Pipeline + Security Scan hoàn tất!"
